// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: follows.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFollow = `-- name: CreateFollow :exec
INSERT INTO follows (followee_id, follower_id, created_at)
VALUES (
    $1,
    $2,
    NOW()
)
`

type CreateFollowParams struct {
	FolloweeID uuid.UUID
	FollowerID uuid.UUID
}

func (q *Queries) CreateFollow(ctx context.Context, arg CreateFollowParams) error {
	_, err := q.db.ExecContext(ctx, createFollow, arg.FolloweeID, arg.FollowerID)
	return err
}

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM follows
WHERE followee_id = $1 AND follower_id = $2
`

type DeleteFollowParams struct {
	FolloweeID uuid.UUID
	FollowerID uuid.UUID
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollow, arg.FolloweeID, arg.FollowerID)
	return err
}

const getFollowees = `-- name: GetFollowees :many
SELECT COUNT(*), followee_id FROM users JOIN follows on users.id = follows.follower_id
WHERE users.id = $1
ORDER BY follows.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFolloweesParams struct {
	ID     uuid.UUID
	Limit  int32
	Offset int32
}

type GetFolloweesRow struct {
	Count      int64
	FolloweeID uuid.UUID
}

func (q *Queries) GetFollowees(ctx context.Context, arg GetFolloweesParams) ([]GetFolloweesRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowees, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFolloweesRow
	for rows.Next() {
		var i GetFolloweesRow
		if err := rows.Scan(&i.Count, &i.FolloweeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowers = `-- name: GetFollowers :many
SELECT COUNT(*), follower_id FROM users JOIN follows on users.id = follows.followee_id
WHERE users.id = $1
ORDER BY follows.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowersParams struct {
	ID     uuid.UUID
	Limit  int32
	Offset int32
}

type GetFollowersRow struct {
	Count      int64
	FollowerID uuid.UUID
}

func (q *Queries) GetFollowers(ctx context.Context, arg GetFollowersParams) ([]GetFollowersRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowers, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowersRow
	for rows.Next() {
		var i GetFollowersRow
		if err := rows.Scan(&i.Count, &i.FollowerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
