// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, title, content, user_id, slug, created_at, updated_at, deleted_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    NOW(),
    NOW(),
    NULL
)
RETURNING id, content, user_id, created_at, updated_at, deleted_at, title, slug
`

type CreatePostParams struct {
	Title   string
	Content string
	UserID  uuid.UUID
	Slug    string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.Title,
		arg.Content,
		arg.UserID,
		arg.Slug,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Title,
		&i.Slug,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
UPDATE posts
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const getAllPosts = `-- name: GetAllPosts :many
SELECT id, content, user_id, created_at, updated_at, deleted_at, title, slug FROM posts WHERE deleted_at is NULL
`

func (q *Queries) GetAllPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getAllPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Title,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostById = `-- name: GetPostById :one
SELECT id, content, user_id, created_at, updated_at, deleted_at, title, slug FROM posts WHERE id = $1 AND deleted_at is NULL
`

func (q *Queries) GetPostById(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostById, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Title,
		&i.Slug,
	)
	return i, err
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT id, content, user_id, created_at, updated_at, deleted_at, title, slug FROM posts WHERE slug = $1 AND deleted_at is NULL
`

func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Title,
		&i.Slug,
	)
	return i, err
}

const getPostsByUser = `-- name: GetPostsByUser :many
SELECT posts.id, title, posts.created_at, posts.updated_at FROM posts JOIN users ON posts.user_id = users.id WHERE deleted_at is NULL AND posts.user_id = $1
`

type GetPostsByUserRow struct {
	ID        uuid.UUID
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetPostsByUser(ctx context.Context, userID uuid.UUID) ([]GetPostsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsByUserRow
	for rows.Next() {
		var i GetPostsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookUpSlug = `-- name: LookUpSlug :one
SELECT COUNT(*) from posts WHERE slug = $1
`

func (q *Queries) LookUpSlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, lookUpSlug, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updatePostInfo = `-- name: UpdatePostInfo :exec
UPDATE posts
SET title = $1, content = $2, updated_at = NOW()
WHERE id = $3
`

type UpdatePostInfoParams struct {
	Title   string
	Content string
	ID      uuid.UUID
}

func (q *Queries) UpdatePostInfo(ctx context.Context, arg UpdatePostInfoParams) error {
	_, err := q.db.ExecContext(ctx, updatePostInfo, arg.Title, arg.Content, arg.ID)
	return err
}
