// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countSearchPosts = `-- name: CountSearchPosts :one
SELECT COUNT(*)
FROM posts
WHERE search_vector @@ plainto_tsquery('english', $1)
`

func (q *Queries) CountSearchPosts(ctx context.Context, plaintoTsquery string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchPosts, plaintoTsquery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, title, content, user_id, created_at, updated_at, deleted_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW(),
    NOW(),
    NULL
)
RETURNING id, content, user_id, created_at, updated_at, deleted_at, title, search_vector
`

type CreatePostParams struct {
	Title   string
	Content string
	UserID  uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.Title, arg.Content, arg.UserID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Title,
		&i.SearchVector,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
UPDATE posts
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const fetchPost = `-- name: FetchPost :many
SELECT id, content, user_id, created_at, updated_at, deleted_at, title, search_vector FROM posts
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type FetchPostParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) FetchPost(ctx context.Context, arg FetchPostParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, fetchPost, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Title,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPosts = `-- name: GetAllPosts :many
SELECT id, content, user_id, created_at, updated_at, deleted_at, title, search_vector FROM posts WHERE deleted_at is NULL
`

func (q *Queries) GetAllPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getAllPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Title,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostById = `-- name: GetPostById :one
SELECT id, content, user_id, created_at, updated_at, deleted_at, title, search_vector FROM posts WHERE id = $1 AND deleted_at is NULL
`

func (q *Queries) GetPostById(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostById, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Title,
		&i.SearchVector,
	)
	return i, err
}

const getPostsByUser = `-- name: GetPostsByUser :many
SELECT id, content, user_id, created_at, updated_at, deleted_at, title, search_vector from posts
WHERE user_id = $1 AND deleted_at is NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetPostsByUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetPostsByUser(ctx context.Context, arg GetPostsByUserParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Title,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsCount = `-- name: GetPostsCount :one
SELECT COUNT(*) FROM posts
WHERE user_id = $1
`

func (q *Queries) GetPostsCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPostsCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchPosts = `-- name: SearchPosts :many
SELECT
  posts.title,
  posts.content,
  posts.created_at,
  posts.updated_at,
  users.username,
  users.id
FROM posts
JOIN users ON posts.user_id = users.id
WHERE posts.search_vector @@ plainto_tsquery('english', $1)
ORDER BY posts.created_at DESC
LIMIT $2 OFFSET $3
`

type SearchPostsParams struct {
	PlaintoTsquery string
	Limit          int32
	Offset         int32
}

type SearchPostsRow struct {
	Title     string
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	ID        uuid.UUID
}

func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPosts, arg.PlaintoTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsRow
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostInfo = `-- name: UpdatePostInfo :exec
UPDATE posts
SET title = $1, content = $2, updated_at = NOW()
WHERE id = $3
`

type UpdatePostInfoParams struct {
	Title   string
	Content string
	ID      uuid.UUID
}

func (q *Queries) UpdatePostInfo(ctx context.Context, arg UpdatePostInfoParams) error {
	_, err := q.db.ExecContext(ctx, updatePostInfo, arg.Title, arg.Content, arg.ID)
	return err
}
