GET http://localhost:8080/users

###
POST http://localhost:8080/users
content-type: application/json

{
    "username": "ha anh tuan",
    "bio": "i master backend development the right way"
}

###
POST http://localhost:8080/users
content-type: application/json

{
    "username": "marco",
    "bio": "i am a stoic mastering the craft of proper software engineering"
}
###
POST http://localhost:8080/posts
content-type: application/json

{
    "user_id": "1edf05b0-9873-4314-84bc-06c894687f18",
    "title": "How I balance between backend development and getting good grades",
    "content": "Just attend class, you know. Just going to class and actually paying attention and interacting with the professors will give you a huge edge, you will be thankful when it's time for final revision. Spend your time in class to do the coursework, then do whatever oyu want at home"
}

###
GET http://localhost:8080/api/refresh

###
GET http://localhost:8080/posts

###
GET http://localhost:8080/posts/e05f452b-7254-4567-b658-ac50a118c069

###
GET http://localhost:8080/posts/e05f452b-7254-4567-b658-ac50a118c061

###
DELETE http://localhost:8080/posts/e05f452b-7254-4567-b658-ac50a118c069

###
GET http://localhost:8080/posts/how-i-balance-between-backend-development-and-getting-good-grades
